"""
Generates a new osm.passenger.trips.xml for the china_osm scenario with:
- 6000 total trips (1000 per 400s window for each of the 6 node begin offsets)
- period = 0.4s  (1000 vehicles per 400 seconds)
- from/to edges are cycled from the original trip file

Node begin offsets: 0, 400, 800, 1200, 1600, 2000s
Each runs for 400 steps -> needs 1000 vehicles in its window.
Total coverage: t=0 to t=2400s => 6000 trips at 0.4s period.
"""
import xml.etree.ElementTree as ET
import os

TARGET_PER_WINDOW = 1000
WINDOW = 400                         # seconds per node episode
NUM_NODES = 6                        # 6 node begin offsets
TOTAL_TRIPS = TARGET_PER_WINDOW * NUM_NODES   # 6000
NEW_PERIOD = WINDOW / TARGET_PER_WINDOW        # 0.4s

TRIP_FILE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    'sumo_configs_china_osm',
    'osm.passenger.trips.xml'
)

# ── 1. Parse original file to get from/to edge pairs ──────────────────────────
tree = ET.parse(TRIP_FILE)
root = tree.getroot()
orig_trips = root.findall('trip')
print(f"Original trips: {len(orig_trips)}")

# Collect full trip attribute dicts — cycle if we need more
trip_attrs = [dict(t.attrib) for t in orig_trips]
num_pairs = len(trip_attrs)

# ── 2. Build new trip elements ─────────────────────────────────────────────────
# Remove existing trips
for t in orig_trips:
    root.remove(t)

for i in range(TOTAL_TRIPS):
    src = trip_attrs[i % num_pairs]              # cycle original attributes
    depart = round(i * NEW_PERIOD, 2)
    trip = ET.SubElement(root, 'trip')
    trip.set('id', str(i))
    trip.set('depart', f'{depart:.2f}')
    trip.set('from', src['from'])
    trip.set('to', src['to'])
    # NOTE: do NOT set 'type' — use SUMO DEFAULT_VEHTYPE to avoid
    # 'vehicle type not known' errors when the network has no custom vtypes

# ── 3. Verify ──────────────────────────────────────────────────────────────────
new_trips = root.findall('trip')
print(f"New total trips: {len(new_trips)}")
begin_offsets = [0, 400, 800, 1200, 1600, 2000]
for begin in begin_offsets:
    count = sum(
        1 for t in new_trips
        if begin <= float(t.get('depart', -1)) < begin + WINDOW
    )
    print(f"  t={begin}-{begin+WINDOW}s: {count} vehicles (target: {TARGET_PER_WINDOW})")

# ── 4. Write file ──────────────────────────────────────────────────────────────
ET.indent(tree, space='    ')
tree.write(TRIP_FILE, encoding='unicode', xml_declaration=False)

with open(TRIP_FILE, 'r', encoding='utf-8') as f:
    content = f.read()

header = (
    '<?xml version="1.0" encoding="UTF-8"?>\n\n'
    f'<!-- Generated by gen_china_osm_trips.py: period={NEW_PERIOD}s, '
    f'{TARGET_PER_WINDOW} vehicles per {WINDOW}s window, {TOTAL_TRIPS} total -->\n\n'
)
with open(TRIP_FILE, 'w', encoding='utf-8') as f:
    f.write(header + content)

print(f"\nDone! Written to {TRIP_FILE}")
print(f"Period={NEW_PERIOD}s | {TARGET_PER_WINDOW} veh/window | {TOTAL_TRIPS} total trips")
